create table dictionary_entry_video_variants (
    id int generated by default as identity primary key,
    dictionary_entry_id int not null references dictionary_entries(id) on delete cascade,
    source_video_file varchar(120) not null,
    region_code varchar(20) not null,
    region_name varchar(80) not null,
    video_url text not null,
    is_default boolean not null default false,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    unique (dictionary_entry_id, source_video_file)
);

create index idx_dictionary_entry_video_variants_entry
    on dictionary_entry_video_variants(dictionary_entry_id);

create index idx_dictionary_entry_video_variants_region
    on dictionary_entry_video_variants(region_code);
