alter table users add column last_seen_at timestamp with time zone;

create table user_activity_events (
    id int generated by default as identity primary key,
    user_email varchar(255) not null,
    event_type varchar(60) not null,
    metadata_json text,
    created_at timestamp with time zone not null default now()
);

create table user_usage_daily (
    user_email varchar(255) not null,
    activity_date date not null,
    active_seconds int not null default 0,
    lesson_completions int not null default 0,
    ai_attempts int not null default 0,
    quiz_attempts int not null default 0,
    last_seen_at timestamp with time zone,
    primary key (user_email, activity_date)
);

create index idx_users_role_active_created
    on users(role, is_active, created_at);

create index idx_users_last_seen
    on users(last_seen_at);

create index idx_user_activity_events_email_created
    on user_activity_events(user_email, created_at desc);

create index idx_user_usage_daily_date
    on user_usage_daily(activity_date, user_email);
