create table dictionary_entries (
    id int generated by default as identity primary key,
    word varchar(120) not null,
    category varchar(80) not null,
    difficulty varchar(20) not null,
    difficulty_level int not null,
    description text not null,
    video_url text,
    thumbnail_url text,
    is_published boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);
