create table dictionary_entries (
    id int generated by default as identity primary key,
    word varchar(120) not null,
    category varchar(80) not null,
    difficulty varchar(20) not null,
    difficulty_level int not null,
    description text not null,
    video_url text,
    thumbnail_url text,
    is_published boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

insert into dictionary_entries (
    id, word, category, difficulty, difficulty_level, description, video_url, thumbnail_url, is_published
)
values
    (1, 'Hello', 'greeting', 'CO_BAN', 1, 'Basic greeting', 'https://cdn.vsign.test/hello.mp4', 'https://cdn.vsign.test/hello.jpg', true),
    (2, 'Thank you', 'greeting', 'CO_BAN', 1, 'Polite phrase', 'https://cdn.vsign.test/thanks.mp4', 'https://cdn.vsign.test/thanks.jpg', true),
    (3, 'School', 'place', 'TRUNG_BINH', 2, 'Place sign', 'https://cdn.vsign.test/school.mp4', 'https://cdn.vsign.test/school.jpg', true),
    (4, 'Family', 'family', 'CO_BAN', 1, 'Family topic', 'https://cdn.vsign.test/family.mp4', 'https://cdn.vsign.test/family.jpg', true),
    (5, 'Market', 'place', 'TRUNG_BINH', 2, 'Market place', 'https://cdn.vsign.test/market.mp4', 'https://cdn.vsign.test/market.jpg', true),
    (6, 'Emergency', 'safety', 'NANG_CAO', 3, 'Advanced safety sign', 'https://cdn.vsign.test/emergency.mp4', 'https://cdn.vsign.test/emergency.jpg', true);
