create table gamification_profiles (
    email varchar(255) primary key,
    user_id varchar(80) not null unique,
    full_name varchar(160) not null,
    avatar_url text,
    total_xp int not null default 0,
    current_streak int not null default 0,
    longest_streak int not null default 0,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table gamification_badges (
    id int generated by default as identity primary key,
    user_id varchar(80) not null,
    badge_id varchar(100) not null,
    name varchar(160) not null,
    earned_at varchar(40) not null
);

create table gamification_xp_awards (
    id int generated by default as identity primary key,
    user_id varchar(80) not null,
    event_id varchar(120) not null,
    source varchar(80) not null,
    xp_delta int not null,
    activity_date date,
    created_at timestamp with time zone not null default now(),
    unique (user_id, event_id)
);
