create table admin_user_accounts (
    id varchar(80) primary key,
    email varchar(255) not null unique,
    display_name varchar(160) not null,
    role varchar(40) not null,
    status varchar(40) not null,
    account_type varchar(40) not null,
    created_at timestamp with time zone not null
);

create table admin_review_queue (
    content_id varchar(120) primary key,
    title varchar(255) not null,
    content_type varchar(60) not null,
    submitted_by varchar(255) not null,
    status varchar(40) not null,
    submitted_at timestamp with time zone not null,
    reviewed_by varchar(255),
    reviewed_at timestamp with time zone,
    reason text
);

create table admin_audit_logs (
    id int generated by default as identity primary key,
    actor_email varchar(255) not null,
    action varchar(80) not null,
    target_type varchar(80) not null,
    target_id varchar(160) not null,
    reason text,
    created_at timestamp with time zone not null default now()
);
