spring.datasource.url=jdbc:h2:mem:vsign_test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;INIT=CREATE SCHEMA IF NOT EXISTS public\\;CREATE DOMAIN IF NOT EXISTS TIMESTAMPTZ AS TIMESTAMP WITH TIME ZONE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.hikari.schema=public
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

DB_SCHEMA=public
spring.config.import=optional:classpath:secretKey-test.properties
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration,classpath:db/testdata
spring.flyway.schemas=public
spring.mvc.servlet.path=/
