-- Generated by scripts/media/generate-video-url-backfill-sql.ps1
-- Generated media URLs must point to the public media delivery domain, not a private object-storage API endpoint.
-- Target schema: v-sign_schema
begin;

do $$
begin
    if to_regclass('"v-sign_schema"."practice_items"') is not null and exists (
        select 1
        from information_schema.columns
        where table_schema = 'v-sign_schema'
          and table_name = 'practice_items'
          and column_name = 'video_url'
    ) then
        update "v-sign_schema"."practice_items" p
        set video_url = v.video_url,
            updated_at = now()
        from (values
        ('practice-hello', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00489.mp4'),
        ('practice-sorry', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W03990.mp4'),
        ('practice-you', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00110B.mp4'),
        ('practice-father', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00325.mp4'),
        ('practice-grandparents', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0151B.mp4'),
        ('practice-parents', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00327.mp4'),
        ('practice-older-brother', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0143B.mp4'),
        ('practice-older-sister', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0144N.mp4'),
        ('practice-eat-drink', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00042.mp4'),
        ('practice-food', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0444.mp4'),
        ('practice-drink', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0443.mp4'),
        ('practice-rice', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00884.mp4'),
        ('practice-restroom', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0485.mp4'),
        ('practice-use-restroom', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0486.mp4'),
        ('practice-preschool', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W03673B.mp4'),
        ('practice-secondary-school', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W03674B.mp4'),
        ('practice-high-school', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W03675B.mp4'),
        ('practice-student-south', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W01658.mp4'),
        ('practice-class-period', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0409.mp4'),
        ('practice-student-board', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00113.mp4'),
        ('practice-address', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0001N.mp4'),
        ('practice-province', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0002.mp4'),
        ('practice-hotel', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W01760.mp4'),
        ('practice-reception', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0003.mp4'),
        ('practice-staff', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0004.mp4'),
        ('practice-emergency', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00432.mp4'),
        ('practice-patient', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00248.mp4'),
        ('practice-illness', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00249.mp4'),
        ('practice-eye-pain', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0355.mp4'),
        ('practice-stomachache', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0356.mp4'),
        ('practice-hand-pain', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0357.mp4'),
        ('practice-leg-pain', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0358.mp4'),
        ('practice-pharmacy', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W01594.mp4'),
        ('practice-bank', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W02348.mp4'),
        ('practice-laptop', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W02151.mp4'),
        ('practice-internet', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0484.mp4'),
        ('practice-police-station', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W01261.mp4'),
        ('practice-law', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W02065.mp4'),
        ('practice-commerce', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0306.mp4'),
        ('practice-import', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0014.mp4'),
        ('practice-one', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0146.mp4'),
        ('practice-two', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0147.mp4'),
        ('practice-three', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0148.mp4'),
        ('practice-four', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0149.mp4'),
        ('practice-five', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0150.mp4'),
        ('practice-one-hour', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0410B.mp4'),
        ('practice-morning', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00368N.mp4'),
        ('practice-evening', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00369B.mp4'),
        ('practice-happy', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W03889B.mp4'),
        ('practice-sad', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0064.mp4'),
        ('practice-scared', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W01650.mp4'),
        ('practice-tired', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0369.mp4'),
        ('practice-beautiful-question', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0128B.mp4'),
        ('practice-not-beautiful', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0129B.mp4'),
        ('practice-bad-person', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W02437B.mp4'),
        ('practice-ability', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0096.mp4'),
        ('practice-airline', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00122.mp4'),
        ('practice-train-driver', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W01920B.mp4'),
        ('practice-bus-stop', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W03534.mp4'),
        ('practice-lost', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0251.mp4'),
        ('practice-tuy-hoa', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0015.mp4'),
        ('practice-quy-nhon', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0016.mp4'),
        ('practice-west', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0009.mp4'),
        ('practice-east', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0010.mp4'),
        ('practice-director', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W01441.mp4'),
        ('practice-female-teacher', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00812B.mp4'),
        ('practice-male-teacher', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W03224B.mp4'),
        ('practice-career', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W02333.mp4'),
        ('practice-work', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W01928.mp4'),
        ('practice-job', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W03835.mp4'),
        ('practice-meeting', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W01677B.mp4'),
        ('practice-sales', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00107B.mp4'),
        ('practice-new-year-greeting', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00664B.mp4'),
        ('practice-mooncake', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00130.mp4'),
        ('practice-mid-autumn', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W03134B.mp4'),
        ('practice-halloween', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0048B.mp4'),
        ('practice-crocodile', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0059.mp4'),
        ('practice-whale', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0073.mp4'),
        ('practice-cat', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00772B.mp4'),
        ('practice-dove', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00602.mp4')
        ) as v(practice_item_id, video_url)
        where p.practice_item_id = v.practice_item_id;
    end if;
end
$$;

do $$
begin
    if to_regclass('"v-sign_schema"."learning_lessons"') is not null and exists (
        select 1
        from information_schema.columns
        where table_schema = 'v-sign_schema'
          and table_name = 'learning_lessons'
          and column_name = 'video_url'
    ) then
        with lesson_video_candidates(lesson_id, video_url, order_index) as (
    values
        ('lesson-greetings-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00489.mp4', 1),
        ('lesson-greetings-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W03990.mp4', 2),
        ('lesson-greetings-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00110B.mp4', 3),
        ('lesson-greetings-2', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00325.mp4', 4),
        ('lesson-greetings-2', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0151B.mp4', 5),
        ('lesson-greetings-2', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00327.mp4', 6),
        ('lesson-greetings-2', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0143B.mp4', 7),
        ('lesson-greetings-2', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0144N.mp4', 8),
        ('lesson-daily-food-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00042.mp4', 9),
        ('lesson-daily-food-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0444.mp4', 10),
        ('lesson-daily-food-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0443.mp4', 11),
        ('lesson-daily-food-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00884.mp4', 12),
        ('lesson-daily-home-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0485.mp4', 13),
        ('lesson-daily-home-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0486.mp4', 14),
        ('lesson-school-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W03673B.mp4', 15),
        ('lesson-school-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W03674B.mp4', 16),
        ('lesson-school-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W03675B.mp4', 17),
        ('lesson-school-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W01658.mp4', 18),
        ('lesson-school-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0409.mp4', 19),
        ('lesson-school-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00113.mp4', 20),
        ('lesson-places-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0001N.mp4', 21),
        ('lesson-places-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0002.mp4', 22),
        ('lesson-places-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W01760.mp4', 23),
        ('lesson-places-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0003.mp4', 24),
        ('lesson-places-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0004.mp4', 25),
        ('lesson-health-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00432.mp4', 26),
        ('lesson-health-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00248.mp4', 27),
        ('lesson-health-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00249.mp4', 28),
        ('lesson-health-2', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0355.mp4', 29),
        ('lesson-health-2', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0356.mp4', 30),
        ('lesson-health-2', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0357.mp4', 31),
        ('lesson-health-2', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0358.mp4', 32),
        ('lesson-health-2', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W01594.mp4', 33),
        ('lesson-tech-business-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W02348.mp4', 34),
        ('lesson-tech-business-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W02151.mp4', 35),
        ('lesson-tech-business-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0484.mp4', 36),
        ('lesson-civic-business-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W01261.mp4', 37),
        ('lesson-civic-business-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W02065.mp4', 38),
        ('lesson-civic-business-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0306.mp4', 39),
        ('lesson-civic-business-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0014.mp4', 40),
        ('lesson-numbers-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0146.mp4', 41),
        ('lesson-numbers-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0147.mp4', 42),
        ('lesson-numbers-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0148.mp4', 43),
        ('lesson-numbers-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0149.mp4', 44),
        ('lesson-numbers-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0150.mp4', 45),
        ('lesson-time-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0410B.mp4', 46),
        ('lesson-time-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00368N.mp4', 47),
        ('lesson-time-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00369B.mp4', 48),
        ('lesson-emotions-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W03889B.mp4', 49),
        ('lesson-emotions-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0064.mp4', 50),
        ('lesson-emotions-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W01650.mp4', 51),
        ('lesson-emotions-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0369.mp4', 52),
        ('lesson-description-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0128B.mp4', 53),
        ('lesson-description-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0129B.mp4', 54),
        ('lesson-description-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W02437B.mp4', 55),
        ('lesson-description-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0096.mp4', 56),
        ('lesson-transport-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00122.mp4', 57),
        ('lesson-transport-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W01920B.mp4', 58),
        ('lesson-transport-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W03534.mp4', 59),
        ('lesson-transport-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0251.mp4', 60),
        ('lesson-geography-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0015.mp4', 61),
        ('lesson-geography-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0016.mp4', 62),
        ('lesson-geography-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0009.mp4', 63),
        ('lesson-geography-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0010.mp4', 64),
        ('lesson-jobs-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W01441.mp4', 65),
        ('lesson-jobs-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00812B.mp4', 66),
        ('lesson-jobs-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W03224B.mp4', 67),
        ('lesson-jobs-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W02333.mp4', 68),
        ('lesson-workplace-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W01928.mp4', 69),
        ('lesson-workplace-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W03835.mp4', 70),
        ('lesson-workplace-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W01677B.mp4', 71),
        ('lesson-workplace-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00107B.mp4', 72),
        ('lesson-holidays-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00664B.mp4', 73),
        ('lesson-holidays-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00130.mp4', 74),
        ('lesson-holidays-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W03134B.mp4', 75),
        ('lesson-holidays-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0048B.mp4', 76),
        ('lesson-animals-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0059.mp4', 77),
        ('lesson-animals-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/D0073.mp4', 78),
        ('lesson-animals-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00772B.mp4', 79),
        ('lesson-animals-1', 'https://pub-aaf79542519744cfaf424549ccf4588c.r2.dev/videos/W00602.mp4', 80)
        ), lesson_videos as (
            select distinct on (lesson_id) lesson_id, video_url
            from lesson_video_candidates
            order by lesson_id, order_index
        )
        update "v-sign_schema"."learning_lessons" l
        set video_url = v.video_url,
            updated_at = now()
        from lesson_videos v
        where l.lesson_id = v.lesson_id
          and (l.video_url is null or l.video_url = '' or l.video_url like 'https://cdn.vsign.test/%');
    end if;
end
$$;
commit;
